# Generated by Django 4.2.27 on 2026-01-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0116_workspacemember_explored_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='github_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
