# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0117_issue_agent_issue_github_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="github_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
